package aprs

// Auto-generated from https://github.com/aprsorg/aprs-deviceid tocalls.yaml
// Licensed under CC BY-SA 2.0 by Hessu, OH7LZB

var tocallDB = []tocallEntry{
	{"AP1WWX", DeviceInfo{"TAPR", "T-238+", "wx"}},
	{"AP4R??", DeviceInfo{"Open Source", "APRS4R", "software"}},
	{"APAEP1", DeviceInfo{"Paraguay Space Agency (AEP)", "EIRUAPRSDIGIS&FV1", "satellite"}},
	{"APAF??", DeviceInfo{"", "AFilter", ""}},
	{"APAG??", DeviceInfo{"", "AGate", ""}},
	{"APAGW", DeviceInfo{"SV2AGW", "AGWtracker", "software"}},
	{"APAGW?", DeviceInfo{"SV2AGW", "AGWtracker", "software"}},
	{"APAH??", DeviceInfo{"", "AHub", ""}},
	{"APAIOR", DeviceInfo{"J. Angelo Racoma DU2XXR/N2RAC", "APRSPH net bot based on Ioreth", "service"}},
	{"APALH*", DeviceInfo{"Retevis", "", ""}},
	{"APALH1", DeviceInfo{"Retevis", "Ailunce H1", "ht"}},
	{"APALHA", DeviceInfo{"Retevis", "Ailunce HA2", "ht"}},
	{"APAM??", DeviceInfo{"Altus Metrum", "AltOS", "tracker"}},
	{"APANC?", DeviceInfo{"John Rokicki, KC1VMZ", "APRS Net Central", "service"}},
	{"APAND?", DeviceInfo{"Open Source", "APRSdroid", "app"}},
	{"APAR??", DeviceInfo{"Øyvind, LA7ECA", "Arctic Tracker", "tracker"}},
	{"APAT16", DeviceInfo{"AnyTone", "AT-D168UV", "ht"}},
	{"APAT51", DeviceInfo{"AnyTone", "AT-D578", "rig"}},
	{"APAT81", DeviceInfo{"AnyTone", "AT-D878", "ht"}},
	{"APAT89", DeviceInfo{"AnyTone", "AT-D890UV", "ht"}},
	{"APAT??", DeviceInfo{"AnyTone", "", ""}},
	{"APATAR", DeviceInfo{"TA7W/OH2UDS Baris Dinc, TA6AD Emre Keles", "ATA-R APRS Digipeater", "digi"}},
	{"APAVR9", DeviceInfo{"NOR", "AVRT9", "ht"}},
	{"APAVT5", DeviceInfo{"SainSonic", "AP510", "tracker"}},
	{"APAW??", DeviceInfo{"SV2AGW", "AGWPE", "software"}},
	{"APAX??", DeviceInfo{"", "AFilterX", ""}},
	{"APB2MF", DeviceInfo{"Mike, DL2MF", "MF2APRS Radiosonde tracking tool", "software"}},
	{"APBK??", DeviceInfo{"PY5BK", "Bravo Tracker", "tracker"}},
	{"APBL??", DeviceInfo{"BigRedBee", "BeeLine GPS", "tracker"}},
	{"APBM??", DeviceInfo{"R3ABM", "BrandMeister DMR", ""}},
	{"APBOX0", DeviceInfo{"SQ9MDD Ryszard Labus", "APRSBox", "daemon"}},
	{"APBPQ?", DeviceInfo{"John Wiseman, G8BPQ", "BPQ32", "software"}},
	{"APBSD?", DeviceInfo{"hambsd.org", "HamBSD", ""}},
	{"APBT*", DeviceInfo{"BTECH", "", ""}},
	{"APBT62", DeviceInfo{"BTECH", "DMR 6x2", "ht"}},
	{"APBT72", DeviceInfo{"BTECH", "DA 7X2", "ht"}},
	{"APBTUV", DeviceInfo{"BTECH", "UV-PRO", "ht"}},
	{"APC???", DeviceInfo{"Rob Wittner, KZ5RW", "APRS/CE", "app"}},
	{"APCDS0", DeviceInfo{"ZS6LMG", "cell tracker", "tracker"}},
	{"APCLEY", DeviceInfo{"ZS6EY", "EYTraker", "tracker"}},
	{"APCLEZ", DeviceInfo{"ZS6EY", "Telit EZ10 GSM application", "tracker"}},
	{"APCLUB", DeviceInfo{"", "Brazil APRS network", ""}},
	{"APCLWX", DeviceInfo{"ZS6EY", "EYWeather", "wx"}},
	{"APCN??", DeviceInfo{"DG5OAW", "carNET", ""}},
	{"APCSMS", DeviceInfo{"USNA", "Cosmos", ""}},
	{"APCSS", DeviceInfo{"AMSAT", "CubeSatSim CubeSat Simulator", ""}},
	{"APCTLK", DeviceInfo{"Open Source", "Codec2Talkie", "app"}},
	{"APCWP8", DeviceInfo{"GM7HHB", "WinphoneAPRS", "app"}},
	{"APD5T?", DeviceInfo{"Geoffrey, F4FXL", "Open Source DStarGateway", "dstar"}},
	{"APDAGW", DeviceInfo{"Diego Guevara, HJ3DAG", "NodeJS APRS WX", "wx"}},
	{"APDF??", DeviceInfo{"", "Automatic DF units", ""}},
	{"APDG??", DeviceInfo{"Jonathan, G4KLX", "ircDDB Gateway", "dstar"}},
	{"APDI??", DeviceInfo{"Bela, HA5DI", "DIXPRS", "software"}},
	{"APDNO?", DeviceInfo{"DO3SWW", "APRSduino", "tracker"}},
	{"APDP25", DeviceInfo{"vk44.net", "Project 25 (P25)", "tracker"}},
	{"APDPRS", DeviceInfo{"unknown", "D-Star APDPRS", "dstar"}},
	{"APDR??", DeviceInfo{"Open Source", "APRSdroid", "app"}},
	{"APDS??", DeviceInfo{"SP9UOB", "dsDIGI", ""}},
	{"APDST?", DeviceInfo{"SP9UOB", "dsTracker", ""}},
	{"APDT??", DeviceInfo{"unknown", "APRStouch Tone (DTMF)", ""}},
	{"APDU??", DeviceInfo{"JA7UDE", "U2APRS", "app"}},
	{"APDV??", DeviceInfo{"OE6PLD", "SSTV with APRS", "software"}},
	{"APDW??", DeviceInfo{"WB2OSZ", "DireWolf", ""}},
	{"APDnnn", DeviceInfo{"Open Source", "aprsd", "software"}},
	{"APE2A?", DeviceInfo{"NoseyNick, VA3NNW", "Email-2-APRS gateway", "software"}},
	{"APE???", DeviceInfo{"", "Telemetry devices", ""}},
	{"APECAN", DeviceInfo{"KT5TK/DL7AD", "Pecan Pico APRS Balloon Tracker", "tracker"}},
	{"APELK?", DeviceInfo{"WB8ELK", "Balloon tracker", "tracker"}},
	{"APEML?", DeviceInfo{"Leszek, SP9MLI", "SP9MLI for WX, Telemetry", "software"}},
	{"APEP??", DeviceInfo{"Patrick EGLOFF, TK5EP", "LoRa WX station", "wx"}},
	{"APERRB", DeviceInfo{"KG5JNC", "APRS Backend for Errbot", "service"}},
	{"APERS?", DeviceInfo{"Jason, KG7YKZ", "Runner tracking", "tracker"}},
	{"APERXQ", DeviceInfo{"PE1RXQ", "PE1RXQ APRS Tracker", "tracker"}},
	{"APESP1", DeviceInfo{"LY3PH", "APRS-ESP", ""}},
	{"APESPG", DeviceInfo{"OH2TH", "ESP SmartBeacon APRS-IS Client", ""}},
	{"APESPW", DeviceInfo{"OH2TH", "ESP Weather Station APRS-IS Client", ""}},
	{"APETBT", DeviceInfo{"PD7R", "TBTracker Balloon Telemetry Tracker", "tracker"}},
	{"APFG??", DeviceInfo{"KP4DJT", "Flood Gage", "software"}},
	{"APFI??", DeviceInfo{"aprs.fi", "", "app"}},
	{"APFII?", DeviceInfo{"aprs.fi", "iPhone/iPad app", "app"}},
	{"APFMN?", DeviceInfo{"Thomas Beiderwieden, DL3EL", "FM-Funknetz HS Dashboard", "service"}},
	{"APFMO?", DeviceInfo{"BG5ESN", "FMO (NFM Over Internet)", "gadget"}},
	{"APFSYC", DeviceInfo{"David McKenzie, K1FSY", "FSY Packet Console", "software"}},
	{"APGBLN", DeviceInfo{"NW5W", "GoBalloon", "tracker"}},
	{"APGDT?", DeviceInfo{"VK4FAST", "Graphic Data Terminal", ""}},
	{"APGKEY", DeviceInfo{"Mohammad Zaki, 9W2KEY", "9W2KEY iGate", "igate"}},
	{"APGO??", DeviceInfo{"AA3NJ", "APRS-Go", "app"}},
	{"APHAX?", DeviceInfo{"PY2UEP", "SM2APRS SondeMonitor", "software"}},
	{"APHBL?", DeviceInfo{"KF7EEL", "HBLink D-APRS Gateway", "software"}},
	{"APHH?", DeviceInfo{"Steven D. Bragg, KA9MVA", "HamHud", "tracker"}},
	{"APHK??", DeviceInfo{"LA1BR", "Digipeater/tracker", ""}},
	{"APHMEY", DeviceInfo{"Tapio Heiskanen, OH2TH", "APRS-IS Client for Athom Homey", ""}},
	{"APHPIA", DeviceInfo{"HP3ICC", "Arduino APRS", ""}},
	{"APHPIB", DeviceInfo{"HP3ICC", "Python APRS Beacon", ""}},
	{"APHPIW", DeviceInfo{"HP3ICC", "Python APRS WX", ""}},
	{"APHRM?", DeviceInfo{"Giovanni, IW1CGW", "Meteo", "wx"}},
	{"APHRT?", DeviceInfo{"Giovanni, IW1CGW", "Telemetry", ""}},
	{"APHT??", DeviceInfo{"IU0AAC", "HMTracker", "tracker"}},
	{"APHW??", DeviceInfo{"HamWAN", "", ""}},
	{"API282", DeviceInfo{"Icom", "IC-2820", "dstar"}},
	{"API31", DeviceInfo{"Icom", "IC-31", "dstar"}},
	{"API410", DeviceInfo{"Icom", "IC-4100", "dstar"}},
	{"API51", DeviceInfo{"Icom", "IC-51", "dstar"}},
	{"API510", DeviceInfo{"Icom", "IC-5100", "dstar"}},
	{"API710", DeviceInfo{"Icom", "IC-7100", "dstar"}},
	{"API80", DeviceInfo{"Icom", "IC-80", "dstar"}},
	{"API880", DeviceInfo{"Icom", "IC-880", "dstar"}},
	{"API910", DeviceInfo{"Icom", "IC-9100", "dstar"}},
	{"API92", DeviceInfo{"Icom", "IC-92", "dstar"}},
	{"API970", DeviceInfo{"Icom", "IC-9700", "dstar"}},
	{"API???", DeviceInfo{"Icom", "unknown", "dstar"}},
	{"APIC??", DeviceInfo{"HA9MCQ", "PICiGATE", ""}},
	{"APIE??", DeviceInfo{"W7KMV", "PiAPRS", ""}},
	{"APIN??", DeviceInfo{"AB0WV", "PinPoint", ""}},
	{"APIZCI", DeviceInfo{"TA7W/OH2UDS Baris Dinc, TA6AD Emre Keles", "hymTR IZCI Tracker", "tracker"}},
	{"APJ8??", DeviceInfo{"KN4CRD", "JS8Call", "software"}},
	{"APJA??", DeviceInfo{"K4HG & AE5PL", "JavAPRS", ""}},
	{"APJE??", DeviceInfo{"Gregg Wonderly, W5GGW", "JeAPRS", ""}},
	{"APJI??", DeviceInfo{"Peter Loveall, AE5PL", "jAPRSIgate", "software"}},
	{"APJID2", DeviceInfo{"Peter Loveall, AE5PL", "D-Star APJID2", "dstar"}},
	{"APJS??", DeviceInfo{"Peter Loveall, AE5PL", "javAPRSSrvr", ""}},
	{"APJY??", DeviceInfo{"KA2DDO", "YAAC", "software"}},
	{"APK003", DeviceInfo{"Kenwood", "TH-D72", "ht"}},
	{"APK004", DeviceInfo{"Kenwood", "TH-D74", "ht"}},
	{"APK005", DeviceInfo{"Kenwood", "TH-D75", "ht"}},
	{"APK0??", DeviceInfo{"Kenwood", "TH-D7", "ht"}},
	{"APK1??", DeviceInfo{"Kenwood", "TM-D700", "rig"}},
	{"APKDXn", DeviceInfo{"KelateDX, 9M2D", "LAHKHUANO APRS", "tracker"}},
	{"APKEYn", DeviceInfo{"9W2KEY", "ESP8266 APRS", "tracker"}},
	{"APKHTW", DeviceInfo{"Kip, W3SN", "Tempest Weather Bridge", "wx"}},
	{"APKRAM", DeviceInfo{"kramstuff.com", "Ham Tracker", "app"}},
	{"APLC??", DeviceInfo{"DL3DCW", "APRScube", ""}},
	{"APLDAG", DeviceInfo{"Inigo, EA2CQ", "DAGA LoRa/APRS SOTA spotting", "service"}},
	{"APLDG?", DeviceInfo{"Eddie, 9W2LWK", "LoRAIGate", "igate"}},
	{"APLDH?", DeviceInfo{"Eddie, 9W2LWK", "LoraTracker", "tracker"}},
	{"APLDI?", DeviceInfo{"David, OK2DDS", "LoRa IGate/Digipeater", "digi"}},
	{"APLDM?", DeviceInfo{"David, OK2DDS", "LoRa Meteostation", "wx"}},
	{"APLER?", DeviceInfo{"Ercan, TA3OER", "TROY LoRa Tracker/iGate", ""}},
	{"APLETK", DeviceInfo{"DL5TKL", "T-Echo", "tracker"}},
	{"APLFG?", DeviceInfo{"Gabor, HG3FUG", "LoRa WX station", "wx"}},
	{"APLFL?", DeviceInfo{"Damian, SQ2CPA", "LoRa/APRS Balloon", "tracker"}},
	{"APLFM?", DeviceInfo{"DO1MA", "FemtoAPRS", "tracker"}},
	{"APLG??", DeviceInfo{"OE5BPA", "LoRa Gateway/Digipeater", "digi"}},
	{"APLHB9", DeviceInfo{"SWISS-ARTG", "LoRa iGate RPI", "igate"}},
	{"APLHI?", DeviceInfo{"Giovanni, IW1CGW", "LoRa IGate/Digipeater/Telemetry", "digi"}},
	{"APLHM?", DeviceInfo{"Giovanni, IW1CGW", "LoRa Meteostation", "wx"}},
	{"APLIF?", DeviceInfo{"TA5Y", "TIF LORA APRS I-GATE", "igate"}},
	{"APLIG?", DeviceInfo{"TA2MUN/TA9OHC", "LightAPRS Tracker", "tracker"}},
	{"APLLO?", DeviceInfo{"HB4LO", "HAB BOT", "tracker"}},
	{"APLM??", DeviceInfo{"WA0TQG", "", "software"}},
	{"APLO??", DeviceInfo{"SQ9MDD", "LoRa KISS TNC/Tracker", "tracker"}},
	{"APLP0?", DeviceInfo{"SQ9P", "fajne digi", "digi"}},
	{"APLP1?", DeviceInfo{"SQ9P", "LORA/FSK/AFSK fajny tracker", "tracker"}},
	{"APLPS?", DeviceInfo{"Jose, XE3JAC", "ESP-32 LoRa", ""}},
	{"APLRF?", DeviceInfo{"Damian, SQ2CPA", "LoRa APRS", ""}},
	{"APLRG?", DeviceInfo{"Ricardo, CA2RXU", "ESP32 LoRa iGate", "igate"}},
	{"APLRM?", DeviceInfo{"Railab Srl, IU2TZK", "Railab LoRa board", "tracker"}},
	{"APLRS?", DeviceInfo{"Railab Srl, IU2TZK", "Railab LoRa board", "igate"}},
	{"APLRT?", DeviceInfo{"Ricardo, CA2RXU", "ESP32 LoRa Tracker", "tracker"}},
	{"APLS??", DeviceInfo{"SARIMESH", "SARIMESH", "software"}},
	{"APLT??", DeviceInfo{"OE5BPA", "LoRa Tracker", "tracker"}},
	{"APLU0?", DeviceInfo{"SP9UP", "ESP32/SX12xx LoRa iGate / Digi", "digi"}},
	{"APLU1?", DeviceInfo{"SP9UP", "ESP32/SX12xx LoRa Tracker", "tracker"}},
	{"APLZA?", DeviceInfo{"Huang Xuewu, BD5HTY", "LoRa", ""}},
	{"APLZX?", DeviceInfo{"N1AF", "LoRa-APRS", ""}},
	{"APM2A?", DeviceInfo{"ZR1RF", "Meshtastic to APRS (mesh2aprs)", "daemon"}},
	{"APMAIL", DeviceInfo{"Mike, NA7Q", "APRS Mailbox", "service"}},
	{"APMBL3", DeviceInfo{"Mobilinkd LLC", "TNC3", "digi"}},
	{"APMBL4", DeviceInfo{"Mobilinkd LLC", "TNC4", "digi"}},
	{"APMBL?", DeviceInfo{"Mobilinkd LLC", "", ""}},
	{"APMBLN", DeviceInfo{"Mobilinkd LLC", "NucleoTNC", "digi"}},
	{"APMDN?", DeviceInfo{"Eric Pasch, KM4TJO", "Meridian APRS", ""}},
	{"APMG??", DeviceInfo{"Alex, AB0TJ", "PiCrumbs and MiniGate", "software"}},
	{"APMI01", DeviceInfo{"Microsat", "WX3in1", ""}},
	{"APMI02", DeviceInfo{"Microsat", "WXEth", ""}},
	{"APMI03", DeviceInfo{"Microsat", "PLXDigi", ""}},
	{"APMI04", DeviceInfo{"Microsat", "WX3in1 Mini", ""}},
	{"APMI05", DeviceInfo{"Microsat", "PLXTracker", ""}},
	{"APMI06", DeviceInfo{"Microsat", "WX3in1 Plus 2.0", ""}},
	{"APMI??", DeviceInfo{"Microsat", "", ""}},
	{"APMON?", DeviceInfo{"Amon Schumann, DL9AS", "APRS Balloon Tracker", "tracker"}},
	{"APMPAD", DeviceInfo{"DF1JSL", "Multi-Purpose APRS Daemon", "service"}},
	{"APMQ??", DeviceInfo{"WB2OSZ", "Ham Radio of Things", ""}},
	{"APMT??", DeviceInfo{"LZ1PPL", "Micro APRS Tracker", "tracker"}},
	{"APN0A?", DeviceInfo{"Jeremy Cooper, KE6JJJ", "N0ARY Full Service Packet BBS", "daemon"}},
	{"APN102", DeviceInfo{"Gregg Wonderly, W5GGW", "APRSNow", "app"}},
	{"APN2??", DeviceInfo{"VE4KLM", "NOSaprs for JNOS 2.0", ""}},
	{"APN3??", DeviceInfo{"Kantronics", "KPC-3", ""}},
	{"APN9??", DeviceInfo{"Kantronics", "KPC-9612", ""}},
	{"APNCM", DeviceInfo{"Keith Kaiser, WA0TJT", "Net Control Manager", "software"}},
	{"APND??", DeviceInfo{"PE1MEW", "DIGI_NED", ""}},
	{"APNEO?", DeviceInfo{"chevybowtie", "nesdr-aprs-igate", "daemon"}},
	{"APNIC4", DeviceInfo{"SQ5EKU", "BidaTrak", "tracker"}},
	{"APNIFC", DeviceInfo{"Mike, NA7Q", "National Interagency Fire Center Alerts", "service"}},
	{"APNJS?", DeviceInfo{"Julien Sansonnens, HB9HRD", "Web messaging service", "service"}},
	{"APNK01", DeviceInfo{"Kenwood", "TM-D700", "rig"}},
	{"APNK80", DeviceInfo{"Kantronics", "KAM", ""}},
	{"APNKMP", DeviceInfo{"Kantronics", "KAM+", ""}},
	{"APNKMX", DeviceInfo{"Kantronics", "KAM-XL", ""}},
	{"APNL??", DeviceInfo{"OE5DXL, OE5HPM", "dxlAPRS", "daemon"}},
	{"APNM??", DeviceInfo{"MFJ", "TNC", ""}},
	{"APNP??", DeviceInfo{"PacComm", "TNC", ""}},
	{"APNT??", DeviceInfo{"SV2AGW", "TNT TNC as a digipeater", "digi"}},
	{"APNU??", DeviceInfo{"IW3FQG", "UIdigi", "digi"}},
	{"APNV0?", DeviceInfo{"SQ8L", "VP-Digi", "digi"}},
	{"APNV1?", DeviceInfo{"SQ8L", "VP-Node", ""}},
	{"APNV2?", DeviceInfo{"SQ8L", "VP-Tracker", "tracker"}},
	{"APNV??", DeviceInfo{"SQ8L", "", ""}},
	{"APNW??", DeviceInfo{"SQ3FYK", "WX3in1", ""}},
	{"APNX??", DeviceInfo{"K6DBG", "TNC-X", ""}},
	{"APOA??", DeviceInfo{"OpenAPRS", "app", "app"}},
	{"APOCSG", DeviceInfo{"N0AGI", "POCSAG", ""}},
	{"APODOT", DeviceInfo{"Mike, NA7Q", "Oregon Department of Transportion Traffic Alerts", "service"}},
	{"APOG7?", DeviceInfo{"OpenGD77", "OpenGD77", ""}},
	{"APOLU?", DeviceInfo{"AMSAT-LU", "Oscar", "satellite"}},
	{"APOMTR", DeviceInfo{"Adrian Craig, M0GLJ", "OZ-TRAK APRS Mobile Tracker", "tracker"}},
	{"APONE?", DeviceInfo{"aprs.one", "", ""}},
	{"APONEA", DeviceInfo{"aprs.one", "Mobile app tracker", "app"}},
	{"APONET", DeviceInfo{"aprs.one", "Hardware tracker", "tracker"}},
	{"APOPEN", DeviceInfo{"David Platt, AE6EO", "OpenTNC", ""}},
	{"APOPYT", DeviceInfo{"Mike, NA7Q", "NA7Q Messenger", "software"}},
	{"APORT?", DeviceInfo{"OpenRTX Contributors", "OpenRTX", ""}},
	{"APOSAT", DeviceInfo{"Mike, NA7Q", "Open Source Satellite Gateway", "service"}},
	{"APOSB", DeviceInfo{"SharkRF", "openSPOT3", "gadget"}},
	{"APOSB4", DeviceInfo{"SharkRF", "openSPOT4", "gadget"}},
	{"APOSB?", DeviceInfo{"SharkRF", "", ""}},
	{"APOSBM", DeviceInfo{"SharkRF", "M1KE", "gadget"}},
	{"APOSMS", DeviceInfo{"Mike, NA7Q", "Open Source SMS Gateway", "service"}},
	{"APOSW?", DeviceInfo{"SharkRF", "openSPOT2", "gadget"}},
	{"APOT??", DeviceInfo{"Argent Data Systems", "OpenTracker", "tracker"}},
	{"APOVU?", DeviceInfo{"K J Somaiya Institute", "BeliefSat", ""}},
	{"APOZ??", DeviceInfo{"OZ1EKD, OZ7HVO", "KissOZ", "tracker"}},
	{"APP6??", DeviceInfo{"", "APRSlib", ""}},
	{"APPCO?", DeviceInfo{"RadCommSoft, LLC", "PicoAPRSTracker", "tracker"}},
	{"APPIC?", DeviceInfo{"DB1NTO", "PicoAPRS", "tracker"}},
	{"APPM??", DeviceInfo{"DL1MX", "rtl-sdr Python iGate", "software"}},
	{"APPRIS", DeviceInfo{"DF1JSL", "Apprise APRS plugin", "service"}},
	{"APPRJ?", DeviceInfo{"Custom Digital Services, LLC", "Traveler's ptFlex and ptSolar trackers", "tracker"}},
	{"APPRO?", DeviceInfo{"KO6IKR", "PyTNC Pro", "software"}},
	{"APPS??", DeviceInfo{"Øyvind, LA7ECA (for the Norwegian Radio Relay League)", "Polaric Server", "software"}},
	{"APPT??", DeviceInfo{"JF6LZE", "KetaiTracker", "tracker"}},
	{"APQCA?", DeviceInfo{"Míra Svoboda, OK1IRY", "ClassicAPRS", "software"}},
	{"APQRX", DeviceInfo{"Jesse Forkum, N0JLF", "QRX - APRS Missed Message Mailbox", "service"}},
	{"APQTH?", DeviceInfo{"Weston Bustraan, W8WJB", "QTH.app", "software"}},
	{"APQUIZ", DeviceInfo{"John Rokicki, KC1VMZ", "QUIZME APRS Quizmaster", "service"}},
	{"APR2MF", DeviceInfo{"Mike, DL2MF", "MF2wxAPRS Tinkerforge gateway", "wx"}},
	{"APR8??", DeviceInfo{"Bob Bruninga, WB4APR", "APRSdos", "software"}},
	{"APRARX", DeviceInfo{"Open Source", "radiosonde_auto_rx", "software"}},
	{"APREST", DeviceInfo{"cwop.rest", "HTTP - TCP CWOP Packet Submission", "service"}},
	{"APRFG?", DeviceInfo{"RF.Guru", "", ""}},
	{"APRFGB", DeviceInfo{"RF.Guru", "APRS LoRa Pager", ""}},
	{"APRFGD", DeviceInfo{"RF.Guru", "APRS Digipeater", "digi"}},
	{"APRFGH", DeviceInfo{"RF.Guru", "Hotspot", "rig"}},
	{"APRFGI", DeviceInfo{"RF.Guru", "LoRa APRS iGate", "igate"}},
	{"APRFGL", DeviceInfo{"RF.Guru", "Lora APRS Digipeater", "digi"}},
	{"APRFGM", DeviceInfo{"RF.Guru", "Mobile Radio", "rig"}},
	{"APRFGP", DeviceInfo{"RF.Guru", "Portable Radio", "ht"}},
	{"APRFGR", DeviceInfo{"RF.Guru", "Repeater", "rig"}},
	{"APRFGT", DeviceInfo{"RF.Guru", "LoRa APRS Tracker", "tracker"}},
	{"APRFGW", DeviceInfo{"RF.Guru", "LoRa APRS Weather Station", "wx"}},
	{"APRFTH", DeviceInfo{"Xian Stannard 2E1IPS & Chung Poon M7UNG", "Treasure Hunt Service", "service"}},
	{"APRG??", DeviceInfo{"OH2GVE", "aprsg", "software"}},
	{"APRHH?", DeviceInfo{"Steven D. Bragg, KA9MVA", "HamHud", "tracker"}},
	{"APRKEY", DeviceInfo{"Mohammad Zaki, 9W2KEY", "MYANET APRS Bot", "service"}},
	{"APRM20", DeviceInfo{"Open Source", "M20 radiosonde", "tracker"}},
	{"APRNFW", DeviceInfo{"Franek SP5FRA", "RS41-NFW", "tracker"}},
	{"APRNOW", DeviceInfo{"Gregg Wonderly, W5GGW", "APRSNow", "app"}},
	{"APRPI?", DeviceInfo{"TA2KVC", "Raspberry Pi APRS / Pico W APRS", "tracker"}},
	{"APRPJB", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS BBS Bot", "service"}},
	{"APRPJC", DeviceInfo{"Piju, 9M2PJU", "9M2PJU Malaysia Callsign Database Bot", "service"}},
	{"APRPJE", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS Echo and Signal Path Bot", "software"}},
	{"APRPJH", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS Heat Bot", "service"}},
	{"APRPJM", DeviceInfo{"Piju, 9M2PJU", "APRSMY Net Bot", "service"}},
	{"APRPJS", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS Web Messenger", "service"}},
	{"APRPJT", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS to Telegram Bot", "service"}},
	{"APRPJU", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS Bot", "daemon"}},
	{"APRPJW", DeviceInfo{"Piju, 9M2PJU", "9M2PJU APRS WX Bot", "service"}},
	{"APRPR?", DeviceInfo{"Robert DM4RW, Peter DL6MAA", "Teensy RPR TNC", "tracker"}},
	{"APRRDZ", DeviceInfo{"DL9RDZ", "rdzTTGOsonde", "tracker"}},
	{"APRRES", DeviceInfo{"xssfox", "APRS-RepeaterRescue", "network"}},
	{"APRRF?", DeviceInfo{"RRF - Réseau des Répéteurs Francophones", "Tracker for RRF", "tracker"}},
	{"APRRT?", DeviceInfo{"RPC Electronics", "RTrak", "tracker"}},
	{"APRS", DeviceInfo{"Unknown", "Unknown", ""}},
	{"APRX??", DeviceInfo{"Kenneth W. Finnegan, W6KWF", "Aprx", "igate"}},
	{"APS???", DeviceInfo{"Brent Hildebrand, KH2Z", "APRS+SA", "software"}},
	{"APSAR", DeviceInfo{"ZL4FOX", "SARTrack", "software"}},
	{"APSC??", DeviceInfo{"OH2MQK, OH7LZB", "aprsc", "software"}},
	{"APSDA?", DeviceInfo{"APSD Developers", "APSD", "software"}},
	{"APSDR?", DeviceInfo{"Marcus Roskosch, DL8MRE", "sdr-control", "app"}},
	{"APSF??", DeviceInfo{"F5OPV, SFCP_LABS", "embedded APRS devices", ""}},
	{"APSFLG", DeviceInfo{"F5OPV, SFCP_LABS", "LoRa/APRS Gateway", "digi"}},
	{"APSFRP", DeviceInfo{"F5OPV, SFCP_LABS", "VHF/UHF Repeater", ""}},
	{"APSFTL", DeviceInfo{"F5OPV, SFCP_LABS", "LoRa/APRS Telemetry Reporter", ""}},
	{"APSFWX", DeviceInfo{"F5OPV, SFCP_LABS", "embedded Weather Station", "wx"}},
	{"APSIGK", DeviceInfo{"Henri Bergius, DF4HB", "Signal K APRS Plugin", "service"}},
	{"APSK63", DeviceInfo{"Chris Moulding, G4HYG", "APRS Messenger", "software"}},
	{"APSMS?", DeviceInfo{"Paul Dufresne", "SMS gateway", "software"}},
	{"APSN01", DeviceInfo{"CSN Technologies Inc.", "iGateMini", ""}},
	{"APSN??", DeviceInfo{"CSN Technologies Inc.", "", ""}},
	{"APSRF?", DeviceInfo{"SoftRF", "Ham Edition", "tracker"}},
	{"APSTAR", DeviceInfo{"AllStar Link LLC", "Asterisk/app_rpt", "daemon"}},
	{"APSTM?", DeviceInfo{"W7QO", "Balloon tracker", "tracker"}},
	{"APSTPO", DeviceInfo{"N0AGI", "Satellite Tracking and Operations", "software"}},
	{"APSVX?", DeviceInfo{"Tobias Blomberg, SM0SVX", "SvxLink", "daemon"}},
	{"APT2??", DeviceInfo{"Byonics", "TinyTrak2", "tracker"}},
	{"APT3??", DeviceInfo{"Byonics", "TinyTrak3", "tracker"}},
	{"APT4??", DeviceInfo{"Byonics", "TinyTrak4", "tracker"}},
	{"APTB??", DeviceInfo{"BG5HHP", "TinyAPRS", ""}},
	{"APTCHE", DeviceInfo{"PU3IKE", "TcheTracker, Tcheduino", "tracker"}},
	{"APTCMA", DeviceInfo{"Cleber, PU1CMA", "CAPI Tracker", "tracker"}},
	{"APTEMP", DeviceInfo{"KL7AF", "APRS-Tempest Weather Gateway", "wx"}},
	{"APTGIK", DeviceInfo{"Juliet Delta, 9M4GIK", "APRS Melaka", ""}},
	{"APTHUR", DeviceInfo{"YD0BCX", "APRSThursday weekly event mapbot daemon", "service"}},
	{"APTKJ?", DeviceInfo{"W9JAJ", "ATTiny APRS Tracker", ""}},
	{"APTKVB", DeviceInfo{"IT9KVB", "Python APRS QTH and Weather-Station", "daemon"}},
	{"APTLVC", DeviceInfo{"TA5LVC", "TR80 APRS Tracker", "tracker"}},
	{"APTNG?", DeviceInfo{"Filip YU1TTN", "Tango Tracker", "tracker"}},
	{"APTPN?", DeviceInfo{"KN4ORB", "TARPN Packet Node Tracker", "tracker"}},
	{"APTR??", DeviceInfo{"Motorola", "MotoTRBO", ""}},
	{"APTSLA", DeviceInfo{"HA2NON", "tesla-aprs", "daemon"}},
	{"APTT*", DeviceInfo{"Byonics", "TinyTrak", "tracker"}},
	{"APTUR?", DeviceInfo{"aprs.ai, TA7HBK", "Türkiye'nin APRS Uygulaması", "app"}},
	{"APTW??", DeviceInfo{"Byonics", "WXTrak", "wx"}},
	{"APU1??", DeviceInfo{"Roger Barker, G4IDE", "UI-View16", "software"}},
	{"APU2*", DeviceInfo{"Roger Barker, G4IDE", "UI-View32", "software"}},
	{"APUDR?", DeviceInfo{"NW Digital Radio", "UDR", ""}},
	{"APVE??", DeviceInfo{"unknown", "EchoLink", ""}},
	{"APVM??", DeviceInfo{"Digital Radio China Club", "DRCC-DVM", "igate"}},
	{"APVR??", DeviceInfo{"unknown", "IRLP", ""}},
	{"APW2W?", DeviceInfo{"Joachim Sonnabend, DG3FBL", "WiresX2Web Software", "software"}},
	{"APW9??", DeviceInfo{"Mile Strk, 9A9Y", "WX Katarina", "wx"}},
	{"APWA??", DeviceInfo{"KJ4ERJ", "APRSISCE", "software"}},
	{"APWEE?", DeviceInfo{"Tom Keffer and Matthew Wall", "WeeWX Weather Software", "software"}},
	{"APWHE?", DeviceInfo{"KF6UFO", "WX-Helios", "wx"}},
	{"APWM??", DeviceInfo{"KJ4ERJ", "APRSISCE", "software"}},
	{"APWW??", DeviceInfo{"KJ4ERJ", "APRSIS32", "software"}},
	{"APWXS?", DeviceInfo{"Colin Cogle, W1DNS", "aprs-weather-submit", "daemon"}},
	{"APWnnn", DeviceInfo{"Sproul Brothers", "WinAPRS", "software"}},
	{"APX???", DeviceInfo{"Open Source", "Xastir", "software"}},
	{"APXR??", DeviceInfo{"G8PZT", "Xrouter", ""}},
	{"APY01D", DeviceInfo{"Yaesu", "FT1D", "ht"}},
	{"APY02D", DeviceInfo{"Yaesu", "FT2D", "ht"}},
	{"APY05D", DeviceInfo{"Yaesu", "FT5D", "ht"}},
	{"APY200", DeviceInfo{"Yaesu", "FTM-200D", "rig"}},
	{"APY300", DeviceInfo{"Yaesu", "FTM-300D", "rig"}},
	{"APY310", DeviceInfo{"Yaesu", "FTM-310D", "rig"}},
	{"APY400", DeviceInfo{"Yaesu", "FTM-400", "rig"}},
	{"APY500", DeviceInfo{"Yaesu", "FTM-500D", "rig"}},
	{"APY510", DeviceInfo{"Yaesu", "FTM-510D", "rig"}},
	{"APYS??", DeviceInfo{"W2GMD", "Python APRS", "software"}},
	{"APYX01", DeviceInfo{"Yaesu", "FTX-1", "rig"}},
	{"APZ*", DeviceInfo{"Unknown", "Experimental", ""}},
	{"APZ18", DeviceInfo{"IW3FQG", "UIdigi", "digi"}},
	{"APZ186", DeviceInfo{"IW3FQG", "UIdigi", "digi"}},
	{"APZ19", DeviceInfo{"IW3FQG", "UIdigi", "digi"}},
	{"APZ247", DeviceInfo{"NR0Q", "UPRS", ""}},
	{"APZG??", DeviceInfo{"OH2GVE", "aprsg", "software"}},
	{"APZMAJ", DeviceInfo{"M1MAJ", "DeLorme inReach Tracker", ""}},
	{"APZMDR", DeviceInfo{"Open Source", "HaMDR", "tracker"}},
	{"APZTKP", DeviceInfo{"Nick Hanks, N0LP", "TrackPoint", "tracker"}},
	{"APZWKR", DeviceInfo{"GM1WKR", "NetSked", "software"}},
	{"APnnnD", DeviceInfo{"Painter Engineering", "uSmartDigi D-Gate", "dstar"}},
	{"APnnnU", DeviceInfo{"Painter Engineering", "uSmartDigi Digipeater", "digi"}},
	{"PSKAPR", DeviceInfo{"Open Source", "PSKmail", "software"}},
}

var miceDB = map[string]DeviceInfo{
	"_ ": {"Yaesu", "VX-8", "ht"},
	"_\\": {"Yaesu", "FTM-350", "rig"},
	"_#": {"Yaesu", "VX-8G", "ht"},
	"_$": {"Yaesu", "FT1D", "ht"},
	"_(": {"Yaesu", "FT2D", "ht"},
	"_0": {"Yaesu", "FT3D", "ht"},
	"_3": {"Yaesu", "FT5D", "ht"},
	"_1": {"Yaesu", "FTM-300D", "rig"},
	"_2": {"Yaesu", "FTM-200D", "rig"},
	"_4": {"Yaesu", "FTM-500D", "rig"},
	"_5": {"Yaesu", "FTM-510D", "rig"},
	"_6": {"Yaesu", "FTX-1", "rig"},
	"_7": {"Yaesu", "FTM-310D", "rig"},
	"_)": {"Yaesu", "FTM-100D", "rig"},
	"_%": {"Yaesu", "FTM-400DR", "rig"},
	"(5": {"Anytone", "D578UV", "ht"},
	"(8": {"Anytone", "D878UV", "ht"},
	"|3": {"Byonics", "TinyTrak3", "tracker"},
	"|4": {"Byonics", "TinyTrak4", "tracker"},
	"^v": {"HinzTec", "anyfrog", ""},
	"*v": {"KissOZ", "Tracker", "tracker"},
	"*9": {"NOR", "AVRT9", "ht"},
	":2": {"SQ8L", "VP-Tracker", "tracker"},
	" X": {"SainSonic", "AP510", "tracker"},
	"[1": {"Open Source", "APRSdroid", "app"},
}

var miceLegacyDB = []miceLegacyEntry{
	{">", "", DeviceInfo{"Kenwood", "TH-D7A", "ht"}},
	{">", "=", DeviceInfo{"Kenwood", "TH-D72", "ht"}},
	{">", "^", DeviceInfo{"Kenwood", "TH-D74", "ht"}},
	{">", "&", DeviceInfo{"Kenwood", "TH-D75", "ht"}},
	{"]", "", DeviceInfo{"Kenwood", "TM-D700", "rig"}},
	{"]", "=", DeviceInfo{"Kenwood", "TM-D710", "rig"}},
}
